from instagrapi import Client
import time
import random

cl = Client()
cl.login_by_sessionid("70016257168%3ATjFKaqSuFT6poD%3A7%3AAYd66AgjBaUKl7K16jHtj3SvVPedLFlSkWWW5VfRqA")

def get_gc_thread_id():
    threads = cl.direct_threads(amount=1)
    for thread in threads:
        if thread.is_group:
            return thread.id
    return None

gc_id = get_gc_thread_id()

# Variation in messages (avoid Insta detection)
messages = [
  "",
    """NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////NICK TERYYY MAAA KAAAAAA BHOOOOOSSDAAAAAA FAAADUNGAAAAAA RANDDIIIKKEEEEE BEEEEEEEEJJJJJJ______////""",
    """NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/NICK GAREEB TERII MA KO L9D DU __/""",
    """NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_NICK TERI MAA RND/_/_/_/_/_""",
    """NICK/CRIMINAL - 𝑇𝐸𝑅𝐼 𝑀𝐴𝑀𝑀𝐼 𝐾𝐼 𝐺𝐴𝑁𝐷 𝐶𝐻𝑂𝐷𝑈 ________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________𝐓𝐔𝐌𝐇𝐀𝐑𝐈 𝐌𝐀𝐀 𝐊𝐀𝐀 𝐁𝐇𝐎𝐒𝐃𝐀 𝐂𝐇𝐎𝐃 𝐃𝐔𝐍𝐆𝐀""",
    """NICK/CRIMINAL - TERI MA KE BUR KA KHOON PILUGA AGR BHAGA TOH\",\n  \"NICK/CRIMINAL - TERI BHEN CHOD DO ___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________ NICK/CRIMINAL - TERI BHN K SATH BHI SUHAGRAT MNAUGA"""
]

# Start spam loop
if gc_id:
    count = 0
    while True:
        msg = random.choice(messages)
        cl.direct_send(msg, [gc_id])
        print(f"Sent: {msg}")
        count += 1

        # Sleep randomly between 15 to 45 seconds
        time.sleep(random.randint(15, 45))

        # Every 30 messages → cooldown for 2 mins
        if count % 30 == 0:
            print("⏸️ Cooldown: Sleeping for 2 minutes...")
            time.sleep(120)
